export const ROUTES = {
  home: '/',
  login: '/login',
  register: '/register',
  dashboard: '/dashboard',
  play: '/play',
  match: (id: string) => `/match/${id}`,
  watch: '/watch',
  watchMatch: (id: string) => `/watch/${id}`,
  profile: '/profile',
  analysis: '/analysis',
  analysisGame: (id: string) => `/analysis/${id}`,
  tournaments: '/tournaments',
  tournament: (id: string) => `/tournaments/${id}`,
  dev: '/dev',
  tools: '/tools',
  arenaNew: '/tools/arena/new',
  arenaList: '/tools/arena',
  arenaCollection: (id: string) => `/tools/arena/${id}`,
  searchDev: '/tools/search',
  gamesDev: '/tools/games',
  lichessPlay: '/tools/lichess',
  anticheatDev: '/dev/anticheat',
} as const
