export const ROUTES = {
  home: '/',
  login: '/login',
  register: '/register',
  dashboard: '/dashboard',
  play: '/play',
  match: (id: string) => `/match/${id}`,
  watch: '/watch',
  watchMatch: (id: string) => `/watch/${id}`,
  profile: '/profile',
  analysis: '/analysis',
  analysisGame: (id: string) => `/analysis/${id}`,
  tournaments: '/tournaments',
  tournament: (id: string) => `/tournaments/${id}`,
  dev: '/dev',
  arenaNew: '/dev/arena/new',
  arenaList: '/dev/arena',
  arenaCollection: (id: string) => `/dev/arena/${id}`,
} as const
